### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by binuzz** [Vedant-Bhalgama/Avyukt#3]
[+] Starting Setup, Please wait ...
Traceback (most recent call last):
  File "/storage/emulated/0/BNK/Avyukt/Avyukt_Setup/setup.py", line 64, in <module>
    setup()

**Comment by Vedant-Bhalgama** [comment]
Please send screenshot of the whole error, I am not able to understand this.

**Comment by binuzz** [comment]
![Screenshot_2020-11-05-20-10-47-653_com.termux.jpg](https://user-images.githubusercontent.com/61690017/98255092-0a6d5600-1fa3-11eb-91e9-6763de21a0b6.jpg)

**Comment by binuzz** [comment]
> Please send screenshot of the whole error, I am not able to understand this.

![Screenshot_2020-11-05-20-10-47-653_com.termux.jpg](https://user-images.githubusercontent.com/61690017/98255207-2b35ab80-1fa3-11eb-879c-c81563fb0c2a.jpg)

**Comment by Vedant-Bhalgama** [comment]
What Python Version are you running it with? Is it Python3? or Python2? Check using this command `python --version
`

**Comment by Vedant-Bhalgama** [comment]
Hello There! 
Can you please tell it? What is the Python Version you are using? I will have to close the issue tomorrow!
