### ISSUE TITLE
raw_input not defined error

### ISSUE THREAD

**Issue by netguardian2019** [Vedant-Bhalgama/Avyukt#4]
I am experiencing the same error with the same screen as the previous correspondent. I am compiling under Python3. Python 2 generated a setup error referring to colorama not found with the python setup.py command in the instructions.

**Comment by netguardian2019** [comment]
Here is the error:

python3 setup.py
    _                    _    _     ____       _               
   / \__   ___   _ _   _| | _| |_  / ___|  ___| |_ _   _ _ __  
  / _ \ \ / / | | | | | | |/ / __| \___ \ / _ \ __| | | | '_ \                                                                                             
 / ___ \ V /| |_| | |_| |   <| |_   ___) |  __/ |_| |_| | |_) |                                                                                            
/_/   \_\_/  \__, |\__,_|_|\_\\__| |____/ \___|\__|\__,_| .__/                                                                                             
             |___/                                      |_|    


[+] Setup File Version 1.0 (Beta)                                                                                                                          
                                                                                                                                                           
[+] Setup Build Date : 23/8/2020                                                                                                                           
                                                                                                                                                           
[+] Detected OS : Linux                                                                                                                                    
                                                                                                                                                           
[+] OS Release : 5.7.0-kali1-amd64                                                                                                                         
                                                                                                                                                           
[+] Starting Setup, Please wait ...                                                                                                                        
Traceback (most recent call last):                                                                                                                         
  File "setup.py", line 66, in <module>                                                                                                                    
    setup()                                                                                                                                                
  File "setup.py", line 23, in setup                                                                                                                       
    start_installation = raw_input("\nAvyukt>: Type y if you want to start installation else n >> ")                                                       
NameError: name 'raw_input' is not defined

**Comment by Vedant-Bhalgama** [comment]
Run with Python2 Please!

**Comment by Vedant-Bhalgama** [comment]
Make sure to read the whole Documentation ... If you are running with Python2 ... Make sure to install these 2 packages first 
`pip install colorama`
`pip install pyfiglet`
